Update azure-kubernetes-service.yml

diff --git a/.github/workflows/azure-kubernetes-service.yml b/.github/workflows/azure-kubernetes-service.yml
--- a/.github/workflows/azure-kubernetes-service.yml
+++ b/.github/workflows/azure-kubernetes-service.yml
@@ -59,29 +59,29 @@ jobs:
             run: terraform init
       
         -   name: Terraform Plan
-            id: tf_plan
+            # id: tf_plan
             working-directory: ./infrastructure 
             run: |
-              terraform plan -detailed-exitcode 
-              echo "exit_code=$?" >> $GITHUB_ENV
+              terraform plan
+              # echo "exit_code=$?" >> $GITHUB_ENV
 
-        -   name: Check Plan Status
-            id: check_plan_status
-            run: |
-              if [ "$exit_code" -eq 0 ]; then
-                echo "No changes detected. Skipping apply."
-                exit 0
-              elif [ "$exit_code" -eq 2 ]; then
-                echo "Changes detected. Proceeding with apply."
-              else
-                echo "Error during plan. Exiting."
-                exit 1
-              fi
-            env:
-              exit_code: ${{ env.exit_code }}
+        # -   name: Check Plan Status
+        #     id: check_plan_status
+        #     run: |
+        #       if [ "$exit_code" -eq 0 ]; then
+        #         echo "No changes detected. Skipping apply."
+        #         exit 0
+        #       elif [ "$exit_code" -eq 2 ]; then
+        #         echo "Changes detected. Proceeding with apply."
+        #       else
+        #         echo "Error during plan. Exiting."
+        #         exit 1
+        #       fi
+        #     env:
+        #       exit_code: ${{ env.exit_code }}
 
         -   name: Terraform Apply
-            if: steps.check_plan_status.outcome == 'success' && env.exit_code == '2'
+            # if: steps.check_plan_status.outcome == 'success' && env.exit_code == '2'
             working-directory: ./infrastructure
             run: terraform apply --auto-approve
               
